# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"\x1e\n\x0b\x42ookRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x42ookResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2L\n\x0b\x42ookService\x12=\n\x12GetBooksByBookName\x12\x11.book.BookRequest\x1a\x12.book.BookResponse\"\x00\x42!\n\x1f\x63om.example.adminjsp.rpcserviceb\x06proto3')



_BOOKREQUEST = DESCRIPTOR.message_types_by_name['BookRequest']
_BOOKRESPONSE = DESCRIPTOR.message_types_by_name['BookResponse']
BookRequest = _reflection.GeneratedProtocolMessageType('BookRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOOKREQUEST,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:book.BookRequest)
  })
_sym_db.RegisterMessage(BookRequest)

BookResponse = _reflection.GeneratedProtocolMessageType('BookResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOOKRESPONSE,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:book.BookResponse)
  })
_sym_db.RegisterMessage(BookResponse)

_BOOKSERVICE = DESCRIPTOR.services_by_name['BookService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037com.example.adminjsp.rpcservice'
  _BOOKREQUEST._serialized_start=20
  _BOOKREQUEST._serialized_end=50
  _BOOKRESPONSE._serialized_start=52
  _BOOKRESPONSE._serialized_end=83
  _BOOKSERVICE._serialized_start=85
  _BOOKSERVICE._serialized_end=161
# @@protoc_insertion_point(module_scope)
